

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  studySidebar: [    
    'study/markdown-guide',
    {
      type: 'category',
      label: '도큐사우르스 시작하기',
      items: [
        'study/docusaurus/docusaurus-start',
        'study/docusaurus/docusaurus-hosting',
        'study/docusaurus/docusaurus-docs',
      ],
    },
    {
      type: 'category',
      label: '이것저것',
      items: [
        'study/etc-guide/nvm-guide',
        'study/etc-guide/ssh-guide',
      ],
    },
  ],
   
};

export default sidebars;
